export const AssignmentNotificationType = {
  ASSIGNMENT_PUBLISHED: "ASSIGNMENT_PUBLISHED",
  ASSIGNMENT_DUE_REMINDER_48H: "ASSIGNMENT_DUE_REMINDER_48H",
  ASSIGNMENT_DUE_REMINDER_24H: "ASSIGNMENT_DUE_REMINDER_24H",
  ASSIGNMENT_OVERDUE: "ASSIGNMENT_OVERDUE",
  SUBMISSION_RECEIVED: "SUBMISSION_RECEIVED",
  SUBMISSION_GRADED: "SUBMISSION_GRADED",
  EXTENSION_GRANTED: "EXTENSION_GRANTED",
  EXTENSION_REQUESTED: "EXTENSION_REQUESTED",
} as const;

export type AssignmentNotificationType = typeof AssignmentNotificationType[keyof typeof AssignmentNotificationType];
